# Generated by Django 5.0.6 on 2024-07-08 04:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coincidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEspecie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('microchip', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('patron', models.CharField(max_length=50)),
                ('esterilizado', models.BooleanField(default=False)),
                ('sociable', models.BooleanField(default=False)),
                ('tratamiento', models.BooleanField(default=False)),
                ('tratamientoDescripcion', models.TextField()),
                ('actividad', models.CharField(max_length=50)),
                ('vacunas', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=200)),
                ('rut_empresa', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('regreso', models.BooleanField(default=False)),
                ('coincidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coincidencia')),
            ],
        ),
        migrations.AddField(
            model_name='coincidencia',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('rol', models.CharField(blank=True, choices=[('adoptante', 'Adoptante'), ('organizacion', 'Organizacion'), ('admin', 'Admin')], max_length=20, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='coincidencia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.CreateModel(
            name='RazaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRaza', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especiemascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.razamascota'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comuna')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEvento', models.CharField(choices=[('Accidente', 'Accidente'), ('Abandono', 'Abandono')], max_length=20)),
                ('userReportante', models.CharField(max_length=200)),
                ('userResponsable', models.CharField(default='No Encontrado', max_length=200)),
                ('mailUserReportante', models.CharField(default='No Encontrado', max_length=200)),
                ('mailUserResponsable', models.CharField(default='No Encontrado', max_length=200)),
                ('sucursal', models.CharField(default='Sin Respuesta', max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('fechaEvento', models.DateTimeField(default=datetime.datetime.now)),
                ('fechaResolucion', models.DateTimeField(blank=True, null=True)),
                ('resolucionObservacion', models.TextField(default='Sin Observacion')),
                ('activo', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('IdSucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('fecha', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='api.mascota')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
